In [1]:
import pandas as pd
import numpy as np
df=pd.read_csv('https://raw.githubusercontent.com/dsrscientist/dataset4/main/Grades.csv')
df

,Seat No.,PH-121,HS-101,CY-105,HS-105/12,MT-111,CS-105,CS-106,EL-102,EE-119,...,CS-312,CS-317,CS-403,CS-421,CS-406,CS-414,CS-419,CS-423,CS-412,CGPA
0,CS-97001,B-,D+,C-,C,C-,D+,D,C-,B-,...,C-,C-,C-,C-,A-,A,C-,B,A-,2.205
1,CS-97002,A,D,D+,D,B-,C,D,A,D+,...,D+,D,C,D,A-,B-,C,C,B,2.008
2,CS-97003,A,B,A,B-,B+,A,B-,B+,A-,...,B,B,A,C,A,A,A,A-,A,3.608
3,CS-97004,D,C+,D+,D,D,A-,D+,C-,D,...,D+,C,D+,C-,B-,B,C+,C+,C+,1.906
4,CS-97005,A-,A-,A-,B+,A,A,A-,B+,A,...,B-,B+,B+,B-,A-,A,A-,A-,A,3.448
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
566,CS-97567,B,A,A,A-,A+,A,A-,A-,A+,...,A-,A-,A,A,A,B+,B+,B,A,3.798
567,CS-97568,A+,A,A,A,A,A,A,A-,A,...,B+,B+,A,A,A-,B,A-,C,A-,3.772
568,CS-97569,B,A,A-,B+,A,A,A,A,A,...,A-,B,A,B+,A,C,B+,A-,A-,3.470
569,CS-97570,A,B+,D,A,D,D+,B-,C-,B-,...,D,B,B,C-,D,C,B,B-,C,2.193
570,CS-97571,C,D,D,C,C,D+,B,C+,C,...,C+,C,B-,D,F,C-,B+,D,C-,1.753

In [2]:
df.nunique()

Seat No.     571
PH-121        13
HS-101        12
CY-105        13
HS-105/12     13
MT-111        13
CS-105        11
CS-106        13
EL-102        13
EE-119        12
ME-107        13
CS-107        14
HS-205/20     13
MT-222        14
EE-222        13
MT-224        14
CS-210        14
CS-211        14
CS-203        13
CS-214        13
EE-217        13
CS-212        12
CS-215        14
MT-331        12
EF-303        12
HS-304        14
CS-301        12
CS-302        11
TC-383        12
MT-442        12
EL-332        13
CS-318        14
CS-306        13
CS-312        14
CS-317        12
CS-403        11
CS-421        13
CS-406        14
CS-414        13
CS-419        12
CS-423        12
CS-412        13
CGPA         491
dtype: int64

In [3]:
df_new= pd.get_dummies(df['PH-121'])

In [4]:
df_new

     A  A+  A-  B  B+  B-  C  C+  C-  D  D+  F  WU
0    0   0   0  0   0   1  0   0   0  0   0  0   0
1    1   0   0  0   0   0  0   0   0  0   0  0   0
2    1   0   0  0   0   0  0   0   0  0   0  0   0
3    0   0   0  0   0   0  0   0   0  1   0  0   0
4    0   0   1  0   0   0  0   0   0  0   0  0   0
..  ..  ..  .. ..  ..  .. ..  ..  .. ..  .. ..  ..
566  0   0   0  1   0   0  0   0   0  0   0  0   0
567  0   1   0  0   0   0  0   0   0  0   0  0   0
568  0   0   0  1   0   0  0   0   0  0   0  0   0
569  1   0   0  0   0   0  0   0   0  0   0  0   0
570  0   0   0  0   0   0  1   0   0  0   0  0   0

[571 rows x 13 columns]

In [5]:
df= pd.concat([df, df_new], axis=1).reindex(df.index)

In [6]:
df

,Seat No.,PH-121,HS-101,CY-105,HS-105/12,MT-111,CS-105,CS-106,EL-102,EE-119,...,B,B+,B-,C,C+,C-,D,D+,F,WU
0,CS-97001,B-,D+,C-,C,C-,D+,D,C-,B-,...,0,0,1,0,0,0,0,0,0,0
1,CS-97002,A,D,D+,D,B-,C,D,A,D+,...,0,0,0,0,0,0,0,0,0,0
2,CS-97003,A,B,A,B-,B+,A,B-,B+,A-,...,0,0,0,0,0,0,0,0,0,0
3,CS-97004,D,C+,D+,D,D,A-,D+,C-,D,...,0,0,0,0,0,0,1,0,0,0
4,CS-97005,A-,A-,A-,B+,A,A,A-,B+,A,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
566,CS-97567,B,A,A,A-,A+,A,A-,A-,A+,...,1,0,0,0,0,0,0,0,0,0
567,CS-97568,A+,A,A,A,A,A,A,A-,A,...,0,0,0,0,0,0,0,0,0,0
568,CS-97569,B,A,A-,B+,A,A,A,A,A,...,1,0,0,0,0,0,0,0,0,0
569,CS-97570,A,B+,D,A,D,D+,B-,C-,B-,...,0,0,0,0,0,0,0,0,0,0
570,CS-97571,C,D,D,C,C,D+,B,C+,C,...,0,0,0,1,0,0,0,0,0,0

In [7]:
df.drop('PH-121', axis=1, inplace=True)

In [8]:
df

,Seat No.,HS-101,CY-105,HS-105/12,MT-111,CS-105,CS-106,EL-102,EE-119,ME-107,...,B,B+,B-,C,C+,C-,D,D+,F,WU
0,CS-97001,D+,C-,C,C-,D+,D,C-,B-,C-,...,0,0,1,0,0,0,0,0,0,0
1,CS-97002,D,D+,D,B-,C,D,A,D+,D,...,0,0,0,0,0,0,0,0,0,0
2,CS-97003,B,A,B-,B+,A,B-,B+,A-,A-,...,0,0,0,0,0,0,0,0,0,0
3,CS-97004,C+,D+,D,D,A-,D+,C-,D,C+,...,0,0,0,0,0,0,1,0,0,0
4,CS-97005,A-,A-,B+,A,A,A-,B+,A,A-,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
566,CS-97567,A,A,A-,A+,A,A-,A-,A+,B+,...,1,0,0,0,0,0,0,0,0,0
567,CS-97568,A,A,A,A,A,A,A-,A,A,...,0,0,0,0,0,0,0,0,0,0
568,CS-97569,A,A-,B+,A,A,A,A,A,B,...,1,0,0,0,0,0,0,0,0,0
569,CS-97570,B+,D,A,D,D+,B-,C-,B-,C-,...,0,0,0,0,0,0,0,0,0,0
570,CS-97571,D,D,C,C,D+,B,C+,C,D+,...,0,0,0,1,0,0,0,0,0,0

In [9]:
df['PH-121'].nunique()

KeyError: 'PH-121'